# Generated by Django 4.2.14 on 2025-11-05 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='is_cleaning',
            field=models.BooleanField(default=False),
        ),
    ]
