# Generated by Django 4.2.14 on 2025-11-05 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_room_is_cleaning'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='is_cleaning',
        ),
    ]
